# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bc668377fc557d104776a58ab15244959495d5da100ac51714e651dce83547fd6c3118cdf87950b59065fb51b6a4b8caada06bb16ca87e0d61c8498efd9af775

test:
  secret_key_base: fcf3afb92da907f6893ad280cf8865edd958d946a495220a7405e9d2676b53e72df80c555a012cd9bf89021778f8f2b919ca8d74078d482b46a63eab0a6b090e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
